name: ESLint

on:
  pull_request:
    branches:
      - main

name: Node.js Lint

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust node version as needed

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn run lint  # Adjust if you have a different npm script for linting