name: Linter

on:
  pull_request:
    branches:
      - main

name: Node.js Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust node version as needed

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache 
      
      - name: Install Prettier
        run: yarn add --dev --exact prettier

      - name: Run ESLint
        run: yarn eslint src/ 

      - name: Run Prettier
        run: yarn prettier src/ 